/**
 * App layout and component styles (tab bar, headers, sections, about, etc.).
 */
import { StyleSheet, StatusBar, Platform } from 'react-native';

const STATUS_BAR_HEIGHT = StatusBar.currentHeight ?? 0;
const HEADER_HEIGHT = STATUS_BAR_HEIGHT + 74;

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#121212',
  },
  container: {
    flex: 1,
    backgroundColor: '#121212',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  scrollView: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingTop: 0,
    marginBottom: 60,
  },
  contentContainer: {
    padding: 20,
    paddingTop: HEADER_HEIGHT,
    paddingBottom: 100,
  },
  errorContainer: {
    backgroundColor: '#2F1515',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    maxWidth: 320,
    borderWidth: 1,
    borderColor: '#CF6679',
  },
  errorTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#CF6679',
    marginBottom: 12,
  },
  errorMessage: {
    fontSize: 16,
    color: '#E1E1E1',
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#BB86FC',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#121212',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#E1E1E1',
  },
  chevron: {
    color: '#BB86FC',
    fontSize: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingRight: 16,
  },
  sectionTitle: {
    fontWeight: 'bold',
    flex: 1,
    color: '#BB86FC',
  },
  sectionContent: {
    paddingLeft: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  titleContainer: {
    marginBottom: 20,
    paddingBottom: 16,
    paddingTop: 12,
    alignItems: 'center',
    position: 'relative',
    borderBottomWidth: 0,
    width: '100%',
  },
  mainTitle: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#BB86FC',
    marginBottom: 16,
    textAlign: 'center',
  },
  titleSummary: {
    fontSize: 18,
    color: '#E1E1E1',
    textAlign: 'center',
    lineHeight: 24,
  },
  centered: {
    alignItems: 'center',
  },
  titleWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  subtitleWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  tocWrapper: {
    width: '90%',
    marginTop: 24,
    marginBottom: 16,
    padding: 16,
    backgroundColor: 'rgba(30, 30, 30, 0.7)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(187, 134, 252, 0.2)',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingTop: StatusBar.currentHeight,
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  /** Search header overlays content; transparent so content scrolls visibly behind it. */
  globalSearchHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: STATUS_BAR_HEIGHT + 10,
    paddingBottom: 8,
    backgroundColor: 'transparent',
    minHeight: HEADER_HEIGHT,
    height: HEADER_HEIGHT,
  },
  spacer: {
    flex: 1,
  },
  searchIconContainer: {
    padding: 8,
    backgroundColor: 'rgba(30, 30, 30, 0.7)',
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchIcon: {
    fontSize: 20,
  },
  searchBarWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 30, 30, 0.9)',
    borderRadius: 8,
    padding: 4,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#2C2C2C',
    color: '#FFFFFF',
    padding: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(187, 134, 252, 0.3)',
  },
  closeIconContainer: {
    padding: 8,
    marginLeft: 8,
  },
  closeIcon: {
    fontSize: 18,
    color: '#E1E1E1',
  },
  highlightedText: {
    backgroundColor: 'rgba(187, 134, 252, 0.3)',
    color: '#ffffff',
    fontWeight: 'bold',
  },
  emptyStateContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 50,
  },
  emptyStateIcon: {
    fontSize: 50,
    marginBottom: 20,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
    textAlign: 'center',
  },
  emptyStateText: {
    fontSize: 16,
    color: '#aaa',
    marginBottom: 10,
    textAlign: 'center',
  },
  mainContainer: {
    flex: 1,
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 68,
    paddingBottom: 8,
    backgroundColor: '#121212',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  activeTabButton: {
    backgroundColor: 'transparent',
  },
  tabButtonInner: {
    alignItems: 'center',
  },
  activeTabButtonInner: {
    backgroundColor: '#BB86FC',
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  tabIconContainer: {
    width: 40,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTabIconContainer: {
    backgroundColor: 'transparent',
  },
  tabIcon: {
    width: 32,
    height: 32,
  },
  activeTabIcon: {
    backgroundColor: 'transparent',
  },
  tabButtonText: {
    fontSize: 10,
    color: '#E1E1E1',
    marginTop: 2,
  },
  activeTabButtonText: {
    color: '#121212',
    fontWeight: '600',
  },
  aboutContainer: {
    padding: 20,
    paddingTop: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: 500,
    alignSelf: 'center',
  },
  aboutTitle: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#BB86FC',
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: 56,
    textShadowColor: 'rgba(187, 134, 252, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  aboutSectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  aboutSectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#BB86FC',
    marginLeft: 10,
  },
  aboutSectionWrapper: {
    marginBottom: 0,
    width: '100%',
  },
  aboutTimestamp: {
    fontSize: 15,
    color: '#E1E1E1',
  },
  paymentSection: {
    marginBottom: 0,
  },
  paymentSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E1E1E1',
    marginBottom: 8,
  },
  amountButtonRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  amountButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(187, 134, 252, 0.5)',
    backgroundColor: 'rgba(30, 30, 30, 0.7)',
  },
  amountButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#BB86FC',
  },
  venmoGridRow: {
    flexDirection: 'row',
    marginBottom: 0,
  },
  venmoGridCell: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  nailButtonWrapper: {
    borderRadius: 12,
    overflow: 'hidden',
    width: '100%',
    alignItems: 'center',
  },
  nailButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 12,
    overflow: 'hidden',
  },
  nailButtonPressed: {
    opacity: 0.8,
  },
  nailImage: {
    width: 88,
    height: 88,
  },
  nailLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#BB86FC',
    marginTop: 8,
  },
  versionContainer: {
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(187, 134, 252, 0.3)',
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: 'rgba(45, 45, 50, 0.75)',
  },
  versionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  versionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  versionText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#BB86FC',
    marginRight: 12,
  },
  versionDate: {
    fontSize: 15,
    color: '#E1E1E1',
    marginRight: 12,
  },
  versionArrow: {
    color: '#BB86FC',
    fontSize: 16,
  },
  versionContentContainer: {
    overflow: 'hidden',
  },
  versionContent: {
    paddingTop: 12,
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 12,
  },
  changelogSubtitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#BB86FC',
    marginBottom: 8,
  },
  changelogItem: {
    fontSize: 16,
    color: '#E1E1E1',
  },
  infoBlock: {
    marginBottom: 16,
  },
  infoBlockLast: {
    marginBottom: 0,
  },
  infoText: {
    fontSize: 15,
    color: '#E1E1E1',
    marginBottom: 6,
    lineHeight: 22,
  },
  infoLink: {
    fontSize: 15,
    color: '#5C7CFA',
    textDecorationLine: 'underline',
  },
  toolDescription: {
    fontSize: 14,
    color: '#E1E1E1',
    lineHeight: 20,
    marginBottom: 12,
  },
  toolDescriptionCode: {
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    backgroundColor: 'rgba(187, 134, 252, 0.15)',
    paddingHorizontal: 4,
    borderRadius: 4,
  },
  toolInputOutputRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  toolInputBlock: {
    flex: 1,
    width: '50%',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  toolOutputBlock: {
    flex: 1,
    width: '50%',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  toolLabelWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  toolLabelIcon: {
    marginRight: 6,
  },
  toolInputLabel: {
    fontSize: 14,
    color: '#E1E1E1',
  },
  toolInputContainer: {
    position: 'relative',
  },
  toolInputPlaceholder: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  toolInputPlaceholderText: {
    fontSize: 16,
    color: '#888',
  },
  toolInput: {
    fontSize: 16,
    color: '#E1E1E1',
    borderWidth: 1,
    borderColor: 'rgba(187, 134, 252, 0.4)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: 'rgba(30, 30, 30, 0.8)',
    width: 80,
    minWidth: 80,
    textAlign: 'center',
  },
  toolInputHidden: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    opacity: 0,
    pointerEvents: 'none',
  },
  toolOutputLabel: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  toolOutputValueWrap: {
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  toolOutputValue: {
    fontSize: 28,
    fontWeight: '600',
    color: '#2E7D32',
  },
  toolQuickRefTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#BB86FC',
    marginTop: 16,
    marginBottom: 8,
  },
  toolTableWrap: {
    borderWidth: 1,
    borderColor: 'rgba(187, 134, 252, 0.35)',
    borderRadius: 8,
    overflow: 'hidden',
  },
  toolTableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(187, 134, 252, 0.25)',
  },
  toolTableRowLast: {
    borderBottomWidth: 0,
  },
  toolTableLabelCell: {
    width: 44,
    paddingVertical: 8,
    paddingHorizontal: 6,
    backgroundColor: 'rgba(45, 45, 50, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolTableLabelText: {
    fontSize: 14,
    color: '#E1E1E1',
    fontWeight: '500',
  },
  toolTableDataCell: {
    flex: 1,
    minWidth: 28,
    paddingVertical: 8,
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(30, 30, 30, 0.6)',
  },
  toolTableDataText: {
    fontSize: 13,
    color: '#E1E1E1',
  },
  toolTableDataTextPlayers: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#3D7DD8',
  },
  toolTableDataTextNails: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  latestBadge: {
    borderWidth: 1,
    borderColor: '#2E7D32',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  latestBadgeText: {
    color: '#2E7D32',
    fontSize: 12,
    fontWeight: 'bold',
  },
  settingsSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E1E1E1',
    marginBottom: 12,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(187, 134, 252, 0.2)',
  },
  settingsRowLabel: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsRowIcon: {
    marginRight: 8,
  },
  settingsRowText: {
    fontSize: 16,
    color: '#E1E1E1',
  },
  settingsRowLast: {
    borderBottomWidth: 0,
  },
  showMatchesButton: {
    backgroundColor: '#BB86FC',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    marginTop: 8,
    marginLeft: 16,
  },
  showMatchesText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
});

export default styles;
export { HEADER_HEIGHT };
